# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default
  vmImage: ubuntu

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'export JAVA_HOME_8_X64=/usr/lib/jvm/java-8-openjdk-amd64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'whoami'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false